=== imr/Electric-VLSI/srcj/com/sun/electric/technology/DRC.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 *
 * Electric(tm) VLSI Design System
 *
 * File: DRC.dtd
 * DRC rules scheme
 *
 * Copyright (c) 2008, Oracle and/or its affiliates. All rights reserved.
 *
 * Electric(tm) is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Electric(tm) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Electric(tm); see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, Mass 02111-1307, USA.
 */
-->

<!-- First attemp to store DRC rules in files -->
<!--<!ELEMENT ruleName (#PCDATA)> -->
 <!ELEMENT DRCRules (Foundry)*>
 <!ELEMENT Foundry ((LayerRule|LayersRule|NodeLayersRule|NodeRule)*)>
 <!ELEMENT LayerRule ANY>   <!-- Rules for particular layers -->
 <!ELEMENT LayersRule ANY>  <!-- Spacing rules between layers -->
 <!ELEMENT NodeLayersRule ANY> <!-- Spacing between layers in a node -->
 <!ELEMENT NodeRule ANY> <!-- special for transistors so far -->
 <!ATTLIST Foundry name CDATA #REQUIRED>
 <!ATTLIST LayerRule
    ruleName CDATA #REQUIRED
    layerName CDATA #REQUIRED
    type (MINWID | MINWIDCOND | MINAREA | MINENCLOSEDAREA | SURROUND) #REQUIRED
    when CDATA #REQUIRED
    value CDATA #REQUIRED
    condition CDATA #IMPLIED
 >
 <!-- value in LayersRule is implied due to COMBINATION -->
 <!ATTLIST LayersRule
    ruleName CDATA #REQUIRED
    layerNames CDATA #REQUIRED
    type (CONSPA | UCONSPA | UCONSPA2D | SPACING | SPACINGE | FORBIDDEN | EXTENSION | EXTENSIONGATE | SURROUND) #REQUIRED
    when CDATA #REQUIRED
    valueX CDATA #IMPLIED
    valueY CDATA #IMPLIED
    value CDATA #IMPLIED
    maxW CDATA #IMPLIED
    minLen CDATA #IMPLIED
    nodeName CDATA #IMPLIED
    condition CDATA #IMPLIED
 >
 <!ATTLIST NodeLayersRule
    ruleName CDATA #REQUIRED
    layerNames CDATA #REQUIRED
    nodeName CDATA #REQUIRED
    type (SURROUND | ASURROUND) #REQUIRED
    when CDATA #REQUIRED
    value CDATA #IMPLIED
    valueX CDATA #IMPLIED
    valueY CDATA #IMPLIED
 >
 <!ATTLIST NodeRule
    ruleName CDATA #REQUIRED
    type (NODSIZ | FORBIDDEN) #REQUIRED
    when CDATA #REQUIRED
    value CDATA #IMPLIED
    valueX CDATA #IMPLIED
    valueY CDATA #IMPLIED
    nodeName CDATA #REQUIRED
 >

=== imr/Electric-VLSI/srcj/com/sun/electric/technology/technologies/utils/Mosis180.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document      : Containing Mosis Rules
    Author        : Gilda G
    Description   : none
-->

<!DOCTYPE DRCRules SYSTEM "DRC.dtd">

<DRCRules>
    <Foundry name="MOSIS">
    <!-- Well rules -->
        <LayerRule ruleName="1.1 Mosis" layerName="P-Well, N-Well, Pseudo-P-Well, Pseudo-N-Well" type="MINWID" when="DE|SU" value="12"/>
        <LayerRule ruleName="1.1 Mosis" layerName="P-Well, N-Well, Pseudo-P-Well, Pseudo-N-Well" type="MINWID" when="SC" value="10"/>
        <LayersRule ruleName="1.2 Mosis" layerNames="{P-Well, P-Well}, {N-Well, N-Well}" type="UCONSPA" when="DE|SU" value="18"/>
        <LayersRule ruleName="1.2 Mosis" layerNames="{P-Well, P-Well}, {N-Well, N-Well}" type="UCONSPA" when="SC" value="9"/>
        <LayersRule ruleName="1.3 Mosis" layerNames="{P-Well, P-Well}, {N-Well, N-Well}" type="CONSPA" when="ALL" value="6"/>
        <LayersRule ruleName="1.4 Mosis" layerNames="{P-Well, N-Well}" type="SPACING" when="ALL" value="0"/>

        <!-- Active rules -->
        <LayerRule ruleName="2.1 Mosis" layerName="P-Active, N-Active" type="MINWID" when="ALL" value="3"/>
        <LayersRule ruleName="2.2 Mosis" layerNames="{P-Active, P-Active}, {N-Active, N-Active}, {P-Active-Well, P-Active-Well}, {P-Active, P-Active-Well}, {N-Active, P-Active-Well}"
            type="SPACING" when="ALL" value="3"/>

        <!-- Active contacts and transistors under DE|SU rules -->
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{N-Well, P-Active}" type="SURROUND" when="DE|SU|NAC" value="6" nodeName="Metal-1-P-Active-Con, P-Transistor"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{N-Well, P-Active}" type="ASURROUND" when="DE|SU" value="6" nodeName="P-Active"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{P-Well, N-Active}" type="SURROUND" when="DE|SU|NAC" value="6" nodeName="Metal-1-N-Active-Con, N-Transistor"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{P-Well, N-Active}" type="ASURROUND" when="DE|SU" value="6" nodeName="N-Active"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{N-Well, P-Active}" type="SURROUND" when="DE|SU|AC" value="6" nodeName="Metal-1-P-Active-Con, P-Transistor"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{P-Well, N-Active}" type="SURROUND" when="DE|SU|AC" value="6" nodeName="Metal-1-N-Active-Con, N-Transistor"/>

        <!-- Active contacts and transistors under SC rules -->
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{N-Well, P-Active}" type="SURROUND" when="SC|NAC" value="5" nodeName="Metal-1-P-Active-Con, P-Transistor"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{P-Well, N-Active}" type="SURROUND" when="SC|NAC" value="5" nodeName="Metal-1-N-Active-Con, N-Transistor"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{N-Well, P-Active}" type="SURROUND" when="SC|AC" value="5" nodeName="Metal-1-P-Active-Con, P-Transistor"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{N-Well, P-Active}" type="ASURROUND" when="SC" value="5" nodeName="P-Active"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{P-Well, N-Active}" type="SURROUND" when="SC|AC" value="5" nodeName="Metal-1-N-Active-Con, N-Transistor"/>
        <NodeLayersRule ruleName="2.3 Mosis" layerNames="{P-Well, N-Active}" type="ASURROUND" when="SC" value="5" nodeName="N-Active" />

        <!-- Well layer -->
        <NodeLayersRule ruleName="2.4 Mosis" layerNames="{P-Well, P-Active-Well}" type="SURROUND" when="ALL" value="3" nodeName="Metal-1-P-Well-Con"/>
        <NodeLayersRule ruleName="2.4 Mosis" layerNames="{N-Well, N-Active}" type="SURROUND" when="ALL" value="3" nodeName="Metal-1-N-Well-Con"/>

        <!-- Active layer -->
        <LayersRule ruleName="2.5 Mosis" layerNames="{P-Active, N-Active}" type="SPACING" when="ALL" value="4"/>

        <!-- polysilicon -->
        <LayerRule ruleName="3.1 Mosis" layerName="Polysilicon-1" type="MINWID" when="ALL" value="2" />
        <LayerRule ruleName="3.1 Mosis" layerName="Transistor-Poly" type="MINWID" when="ALL" value="2" />
        <LayersRule ruleName="3.2 Mosis" layerNames="{Polysilicon-1, Polysilicon-1}" type="SPACING" when="DE|SU" value="3"/>
        <LayersRule ruleName="3.2 Mosis" layerNames="{Polysilicon-1, Transistor-Poly}" type="SPACING" when="DE|SU" value="3"/>
        <LayersRule ruleName="3.2 Mosis" layerNames="{Polysilicon-1, Polysilicon-1}" type="SPACING" when="SC" value="2"/>
        <LayersRule ruleName="3.2 Mosis" layerNames="{Polysilicon-1, Transistor-Poly}" type="SPACING" when="SC" value="2"/>
        <LayersRule ruleName="3.2a Mosis" layerNames="{Transistor-Poly, Transistor-Poly}" type="SPACING" when="DE" value="4"/>
        <LayersRule ruleName="3.2a Mosis" layerNames="{Transistor-Poly, Transistor-Poly}" type="SPACING" when="SU" value="3"/>
        <LayersRule ruleName="3.2a Mosis" layerNames="{Transistor-Poly, Transistor-Poly}" type="SPACING" when="SC" value="2"/>

        <!-- Transistor poly Valid for N-Transistor, P-Transistor and scalable transistors -->
        <LayersRule ruleName="3.3 Mosis" layerNames="{Transistor-Poly, P-Active}, {Transistor-Poly, N-Active}" type="EXTENSION" when="DE" value="2.5"/> <!-- Poly from active -->
        <LayersRule ruleName="3.3 Mosis" layerNames="{Transistor-Poly, P-Active}, {Transistor-Poly, N-Active}" type="EXTENSION" when="SU|SC" value="2"/> <!-- Poly from active -->
        <LayersRule ruleName="OD.C.6 TSMC" layerNames="{P-Active, Transistor-Poly}, {N-Active, Transistor-Poly}" type="EXTENSION" when="DE" value="4"/> <!-- Active from poly -->
        <LayersRule ruleName="OD.C.6 TSMC" layerNames="{P-Active, Transistor-Poly}, {N-Active, Transistor-Poly}" type="EXTENSION" when="SU|SC" value="3"/> <!-- Active from poly -->
        <NodeLayersRule ruleName="Trans SelPoly Surround Mosis" layerNames="{P-Select, Transistor-Poly}" type="SURROUND" when="ALL" value="2" nodeName="P-Transistor"/>
        <NodeLayersRule ruleName="Trans SelPoly Surround Mosis" layerNames="{N-Select, Transistor-Poly}" type="SURROUND" when="ALL" value="2" nodeName="N-Transistor"/>

        <!-- Poly and active layers -->
         <LayersRule ruleName="3.5 Mosis" layerNames="{Polysilicon-1, P-Active}, {Transistor-Poly, P-Active}, {Polysilicon-1, N-Active},
         {Transistor-Poly, N-Active}, {Polysilicon-1,  P-Active-Well}, {Transistor-Poly, P-Active-Well}"
             type="SPACING" when="ALL" value="1"/>

        <!-- Select layers -->
        <!-- Data for transistors and active contacts -->
        <NodeLayersRule ruleName="4.2 Mosis" layerNames="{P-Select, P-Active}" type="SURROUND" when="ALL" value="2" nodeName="Metal-1-P-Active-Con, P-Transistor"/>
        <NodeLayersRule ruleName="4.2 Mosis" layerNames="{P-Select, P-Active-Well}" type="SURROUND" when="ALL" value="2" nodeName="Metal-1-P-Well-Con"/>
        <NodeLayersRule ruleName="4.2 Mosis" layerNames="{N-Select, N-Active}" type="SURROUND" when="ALL" value="2" nodeName="Metal-1-N-Active-Con, N-Transistor, Metal-1-N-Well-Con"/>

        <LayerRule ruleName="4.4 Mosis" layerName="P-Select, N-Select, Pseudo-P-Select, Pseudo-N-Select" type="MINWID" when="DE" value="4" />
        <LayersRule ruleName="4.4 Mosis" layerNames="{P-Select, P-Select}, {N-Select, N-Select}" type="SPACING" when="DE" value="4"/>
        <LayerRule ruleName="4.4 Mosis" layerName="P-Select, N-Select, Pseudo-P-Select, Pseudo-N-Select" type="MINWID" when="SU|SC" value="2" />
        <LayersRule ruleName="4.4 Mosis" layerNames="{P-Select, P-Select}, {N-Select, N-Select}" type="SPACING" when="SU|SC" value="2"/>

        <LayersRule ruleName="4.4 Mosis" layerNames="{P-Select, N-Select}" type="SPACING" when="ALL" value="0"/>

        <!-- Poly cut -->
        <LayerRule ruleName="5.1 Mosis" layerName="Poly-Cut" type="MINWID" when="ALL" value="2" />

        <!-- Poly contact -->
        <NodeRule ruleName="5.2 Mosis" type="NODSIZ" when="NAC" value="5" nodeName="Metal-1-Polysilicon-1-Con"/>
        <NodeLayersRule ruleName="5.2 Mosis" layerNames="{Polysilicon-1,  Metal-1}" type="SURROUND" when="NAC" value="0.5" nodeName="Metal-1-Polysilicon-1-Con"/>
        <LayersRule ruleName="5.2 Mosis" layerNames="{Polysilicon-1, Poly-Cut}" type="SURROUND" when="NAC" value="1.5"/>
        <NodeRule ruleName="5.2b Mosis" type="NODSIZ" when="AC" value="4" nodeName="Metal-1-Polysilicon-1-Con"/>
        <NodeLayersRule ruleName="5.2b Mosis" layerNames="{Polysilicon-1,  Metal-1}" type="SURROUND" when="AC" value="0" nodeName="Metal-1-Polysilicon-1-Con"/>
        <LayersRule ruleName="5.2b Mosis" layerNames="{Polysilicon-1, Poly-Cut}" type="SURROUND" when="AC" value="1"/>

        <!-- Multi poly contacts -->
        <LayersRule ruleName="5.3 Mosis" layerNames="{Poly-Cut, Poly-Cut}" type="SPACING" when="DE" value="4"/>
        <LayersRule ruleName="5.3,6.3 Mosis" layerNames="{Active-Cut, Poly-Cut}" type="SPACING" when="DE|NAC" value="4"/>

        <LayersRule ruleName="5.3 Mosis" layerNames="{Poly-Cut, Poly-Cut}" type="SPACING" when="SC" value="2"/>
        <LayersRule ruleName="5.3,6.3 Mosis" layerNames="{Active-Cut, Poly-Cut}" type="SPACING" when="SC|NAC" value="2"/>

        <LayersRule ruleName="5.3 Mosis" layerNames="{Poly-Cut, Poly-Cut}" type="SPACING" when="SU" value="3"/>
        <LayersRule ruleName="5.3,6.3 Mosis" layerNames="{Active-Cut, Poly-Cut}" type="SPACING" when="SU|NAC" value="3"/>

        <LayersRule ruleName="5.4 Mosis" layerNames="{Poly-Cut, Transistor-Poly}" type="SPACING" when="ALL" value="2"/>

        <LayersRule ruleName="5.5b Mosis" layerNames="{Poly-Cut, Polysilicon-1}" type="UCONSPA" when="DE|SU|AC" value="5"/>
        <LayersRule ruleName="5.5b Mosis" layerNames="{Poly-Cut, Transistor-Poly}" type="UCONSPA" when="DE|SU|AC" value="5"/>
        <LayersRule ruleName="5.5b Mosis" layerNames="{Poly-Cut, Polysilicon-1}" type="UCONSPA" when="SC|AC" value="4"/>
